print ("Nama: Muhammad Agung Santoso")
print ("NIM : 182410103081")
print ("Algoritma dan Pemrograman II F")


print("*            *")
print(" *          *")
print("  *        *")
print("   *      *")
print("    *    *")
print("     *  *")
print("      **")
print("      **")
print("      **")
print("      **")
print("      **")
print("      **")
